# Generated by Django 5.0.7 on 2026-02-09 23:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('anio', models.PositiveIntegerField()),
                ('km_actuales', models.PositiveIntegerField(default=0)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='workorders.owner')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_DIAGNOSTICO', 'En Diagnostico'), ('PRESUPUESTADA', 'Presupuestada'), ('APROBADA', 'Aprobada'), ('EN_REPARACION', 'En Reparacion'), ('EN_ESPERA', 'En Espera'), ('PRUEBA_PISTA', 'Prueba Pista'), ('CERRADA', 'Cerrada'), ('FACTURADA', 'Facturada'), ('ENTREGADA', 'Entregada')], default='ABIERTA', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion_problema', models.TextField()),
                ('odometer_km', models.PositiveIntegerField()),
                ('bahia', models.CharField(blank=True, max_length=20, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='workorders.owner')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='workorders.vehicle')),
            ],
        ),
    ]
