# Generated by Django 6.0.2 on 2026-02-10 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "especialidad",
                    models.CharField(
                        choices=[
                            ("MOTOR", "Motor"),
                            ("TRANSMISION", "Transmisión"),
                            ("SUSPENSION", "Suspensión"),
                            ("ELECTRICO", "Eléctrico"),
                            ("GENERAL", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("JUNIOR", "Junior"),
                            ("INTERMEDIO", "Intermedio"),
                            ("EXPERTO", "Experto"),
                        ],
                        max_length=15,
                    ),
                ),
                ("tarifa_hora", models.DecimalField(decimal_places=2, max_digits=10)),
                ("disponible", models.BooleanField(default=True)),
                ("horas_pendientes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ComponentePredictivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("km_promedio_fallo", models.IntegerField()),
                ("desviacion_estandar", models.FloatField()),
                (
                    "vehiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="workorders.vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workorder",
            name="mecanico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ordenes",
                to="workorders.mechanic",
            ),
        ),
    ]
