# Generated by Django 6.0.2 on 2026-03-01 02:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_mechanic_componentepredictivo_workorder_mecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentepredictivo',
            name='categoria',
            field=models.CharField(choices=[('MOTOR', 'Motor'), ('TRANSMISION', 'Transmisión'), ('SUSPENSION', 'Suspensión'), ('FRENOS', 'Frenos'), ('ELECTRICO', 'Eléctrico'), ('CARROCERIA', 'Carrocería'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='componentepredictivo',
            name='costo_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='componentepredictivo',
            name='modelo_vehiculo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='eficiencia',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='owner',
            name='descuento_acumulado',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='owner',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='owner',
            name='tipo_cliente',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('VIP', 'VIP'), ('PREMIUM', 'Premium')], default='REGULAR', max_length=10),
        ),
        migrations.AddField(
            model_name='owner',
            name='total_gastado_mes',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
        migrations.AddField(
            model_name='workorder',
            name='costo_presupuestado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='costo_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workorder',
            name='fecha_estimada_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tiempo_estimado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tiempo_real',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FacturaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=15)),
                ('dias_garantia', models.PositiveIntegerField(default=30)),
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='workorders.workorder')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='workorders.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ParteMecanica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_oem', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('MOTOR', 'Motor'), ('TRANSMISION', 'Transmisión'), ('SUSPENSION', 'Suspensión'), ('FRENOS', 'Frenos'), ('ELECTRICO', 'Eléctrico'), ('CARROCERIA', 'Carrocería'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ordenes', models.ManyToManyField(blank=True, related_name='partes', to='workorders.workorder')),
            ],
        ),
    ]
