# Generated by Django 5.2.4 on 2026-03-01 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorders", "0003_componentepredictivo_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="placa",
            field=models.CharField(
                max_length=6,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Formato inválido. La placa colombiana debe ser 3 letras + 3 números (Ej: ABC123)",
                        regex="^[A-Z]{3}[0-9]{3}$",
                    )
                ],
            ),
        ),
    ]
