# Generated by Django 5.2.14 on 2026-05-22 02:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_alter_vehicle_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MOTOR', 'Motor'), ('TRANSMISION', 'Transmisión'), ('SUSPENSION', 'Suspensión'), ('FRENOS', 'Frenos'), ('ELECTRICO', 'Eléctrico'), ('CARROCERIA', 'Carrocería'), ('GENERAL', 'General')], max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bahia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('MECANICA', 'Mecánica'), ('ELECTRICA', 'Eléctrica'), ('CARROCERIA', 'Carrocería'), ('ALINEACION', 'Alineación')], default='GENERAL', max_length=15)),
                ('activa', models.BooleanField(default=True)),
                ('orden_actual', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bahia_asignada', to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.checklisttemplate')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MOTOR', 'Motor'), ('TRANSMISION', 'Transmisión'), ('SUSPENSION', 'Suspensión'), ('FRENOS', 'Frenos'), ('ELECTRICO', 'Eléctrico'), ('CARROCERIA', 'Carrocería'), ('GENERAL', 'General')], max_length=20)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='workorders.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('OK', 'OK'), ('REVISAR', 'A revisar'), ('FALLA', 'Falla'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=12)),
                ('nota', models.CharField(blank=True, default='', max_length=300)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorders.diagnosticochecklist')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/')),
                ('momento', models.CharField(choices=[('ANTES', 'Antes'), ('DURANTE', 'Durante'), ('DESPUES', 'Después')], default='ANTES', max_length=10)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='workorders.workorder')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='TimerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('nota', models.CharField(blank=True, default='', max_length=200)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timers', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
